{
 "swagger": "2.0",
 "info": {
  "description": "The Platform REST API lets you integrate with Rose Rocket applications using simple HTTP methods, in JSON formats, making this an ideal API for developing mobile applications or external clients.",
  "version": "1.0.0",
  "title": "Rose Rocket Platform REST API",
  "termsOfService": "http://swagger.io/terms/",
  "contact": {
   "email": "platform@roserocket.com"
  }
 },
 "host": "platform.roserocket.com",
 "basePath": "/v1",
 "tags": [
  {
   "name": "order",
   "description": "Manage orders"
  },
  {
   "name": "quote",
   "description": "Manage quotes"
  },
  {
   "name": "customer",
   "description": "Manage customers"
  }
 ],
 "schemes": [
  "https"
 ],
 "paths": {
  "/orders": {
   "get": {
    "tags": [
     "order"
    ],
    "summary": "Search orders",
    "description": "",
    "operationId": "searchOrders",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/orders": {
   "post": {
    "tags": [
     "order"
    ],
    "summary": "Create new customer's order",
    "description": "",
    "operationId": "createOrder",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/orders/bulk_create": {
   "post": {
    "tags": [
     "order"
    ],
    "summary": "Bulk create orders for a given customer.",
    "description": "",
    "operationId": "bulkCreateOrder",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/orders/bulk_create": {
   "post": {
    "tags": [
     "order"
    ],
    "summary": "Bulk create orders for several customers.",
    "description": "",
    "operationId": "bulkCreateOrderCustomerAgnostic",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/bulk_create_booked_order": {
   "post": {
    "tags": [
     "order"
    ],
    "summary": "Bulk create booked orders for a given customer.",
    "description": "",
    "operationId": "bulkCreateBookedOrder",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/orders/bulk_create_booked_order": {
   "post": {
    "tags": [
     "order"
    ],
    "summary": "Bulk create booked orders for several customers.",
    "description": "",
    "operationId": "bulkCreateBookedOrderCustomerAgnostic",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/orders/bulk_upsert_booked_order": {
   "post": {
    "tags": [
     "order"
    ],
    "summary": "Upsert orders for several customers.",
    "description": "",
    "operationId": "bulkUpsertBookedOrderCustomerAgnostic",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/orders/{orderID}/revise_origin": {
   "put": {
    "tags": [
     "order"
    ],
    "summary": "Revise the origin of an order by ID",
    "description": "",
    "operationId": "reviseOrderOriginByID",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/orders/{orderID}/revise_destination": {
   "put": {
    "tags": [
     "order"
    ],
    "summary": "Revise the destination of an order by ID",
    "description": "",
    "operationId": "reviseOrderDestinationByID",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/orders/{orderID}/revise_commodities": {
   "put": {
    "tags": [
     "order"
    ],
    "summary": "Revise the commodities of an order by ID",
    "description": "",
    "operationId": "reviseOrderCommoditiesByID",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/orders/{orderID}/events/internal_notes": {
   "get": {
    "tags": [
     "order"
    ],
    "summary": "Get an internal event by orderID",
    "description": "",
    "operationId": "getOrderInternalEventByOrderID",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/orders/{orderID}": {
   "get": {
    "tags": [
     "order"
    ],
    "summary": "Get customer's order by ID",
    "description": "",
    "operationId": "getOrderByID",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "order"
    ],
    "summary": "Update customer's order by ID",
    "description": "",
    "operationId": "updateOrderByID",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "order"
    ],
    "summary": "Delete customer's order by ID",
    "description": "",
    "operationId": "deleteOrderByID",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/create_booked_order": {
   "post": {
    "tags": [
     "order"
    ],
    "summary": "Create a booked order",
    "description": "",
    "operationId": "createBookedOrder",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/legs": {
   "get": {
    "tags": [
     "leg"
    ],
    "summary": "Search legs",
    "description": "",
    "operationId": "searchLegs",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   }
  },
  "/legs/{legID}/revise_origin": {
   "put": {
    "tags": [
     "leg"
    ],
    "summary": "Revise the origin of a leg by ID",
    "description": "",
    "operationId": "reviseLegOriginById",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   }
  },
  "/legs/{legID}/revise_destination": {
   "put": {
    "tags": [
     "leg"
    ],
    "summary": "Revise the destination of a leg by ID",
    "description": "",
    "operationId": "reviseLegDestinationById",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   }
  },
  "/legs/{legID}/revise_commodities": {
   "put": {
    "tags": [
     "leg"
    ],
    "summary": "Revise the commodities of a leg by ID",
    "description": "",
    "operationId": "reviseLegCommoditiesById",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   }
  },
  "/legs/{legID}/load": {
   "post": {
    "tags": [
     "leg"
    ],
    "summary": "Load leg by ID",
    "description": "",
    "operationId": "loadLegById",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   }
  },
  "/legs/{legID}/unload": {
   "post": {
    "tags": [
     "leg"
    ],
    "summary": "Unload leg by ID",
    "description": "",
    "operationId": "unloadLegById",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   }
  },
  "/legs/{legID}/files/{fileID}": {
   "put": {
    "tags": [
     "leg"
    ],
    "summary": "Add a file/document to a specified leg",
    "description": "",
    "operationId": "updateLegFileByLegIdAndFileID",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "leg"
    ],
    "summary": "Delete a file/document from a specified leg",
    "description": "",
    "operationId": "deleteLegFileByLegIdAndFileID",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   }
  },
  "/legs/{legID}/files": {
   "get": {
    "tags": [
     "leg"
    ],
    "summary": "Get all leg files/documents for a given ID of a leg",
    "description": "",
    "operationId": "getLegFilesById",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "leg"
    ],
    "summary": "Add a file/document to a specified leg",
    "description": "",
    "operationId": "addLegFileByLegId",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   }
  },
  "/legs/{legID}/upload_bol": {
   "post": {
    "tags": [
     "leg"
    ],
    "summary": "Upload BOL for a specified leg",
    "description": "",
    "operationId": "uploadLegBOLByLegID"
   }
  },
  "/legs/{legID}/upload_file": {
   "post": {
    "tags": [
     "leg"
    ],
    "summary": "Upload file for a specified leg",
    "description": "",
    "operationId": "uploadLegFileByLegID"
   }
  },
  "/legs/{legID}/upload_file/{fileID}": {
   "put": {
    "tags": [
     "leg"
    ],
    "summary": "Update an uploaded file for a specified leg",
    "description": "",
    "operationId": "updateUploadedFileByLegAndFileID"
   }
  },
  "/orders/{orderID}": {
   "get": {
    "tags": [
     "order"
    ],
    "summary": "Get order by Rose Rocket order ID",
    "description": "",
    "operationId": "getOrderByRRID",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/orders/{orderID}/legs": {
   "get": {
    "tags": [
     "leg"
    ],
    "summary": "Get legs by order ID",
    "description": "",
    "operationId": "getLegsByOrder",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/orders/{orderID}/files": {
   "get": {
    "tags": [
     "order"
    ],
    "summary": "Get all leg files/documents for a given ID of a leg",
    "description": "",
    "operationId": "getOrderFilesById",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "order"
    ],
    "summary": "Add a file/document to a specified order",
    "description": "",
    "operationId": "addOrderFileByLegId",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/orders/{orderID}/files/{fileID}": {
   "put": {
    "tags": [
     "order"
    ],
    "summary": "Update a file for a specified order",
    "description": "",
    "operationId": "updateFileByOrderAndFileID"
   },
   "delete": {
    "tags": [
     "order"
    ],
    "summary": "Delete a file for a specified order",
    "description": "",
    "operationId": "deleteFileByOrderAndFileID"
   }
  },
  "/customers/{customerID}/orders/{orderID}/upload_bol": {
   "post": {
    "tags": [
     "order"
    ],
    "summary": "Upload BOL for a specified order",
    "description": "",
    "operationId": "uploadOrderBOL"
   }
  },
  "/customers/{customerID}/orders/{orderID}/upload_file": {
   "post": {
    "tags": [
     "order"
    ],
    "summary": "Upload file for a specified order",
    "description": "",
    "operationId": "uploadOrderFile"
   }
  },
  "/customers/{customerID}/orders/{orderID}/upload_file/{fileID}": {
   "put": {
    "tags": [
     "order"
    ],
    "summary": "Update an uploaded file for a specified order",
    "description": "",
    "operationId": "updateOrderFile"
   }
  },
  "/legs/{legID}": {
   "get": {
    "tags": [
     "leg"
    ],
    "summary": "Get leg by ID",
    "description": "",
    "operationId": "getLegByID",
    "security": [
     {
      "roserocket_auth": [
       "legs"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}": {
   "get": {
    "tags": [
     "manifest"
    ],
    "summary": "Get manifest by ID",
    "description": "",
    "operationId": "getManifestByID",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests": {
   "post": {
    "tags": [
     "manifest"
    ],
    "summary": "Create a new manifest",
    "description": "",
    "operationId": "createManifest",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/assign_driver": {
   "post": {
    "tags": [
     "manifest"
    ],
    "summary": "Assign a driver to a manifest",
    "description": "",
    "operationId": "assignDriverToManifest",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/assign_carrier": {
   "post": {
    "tags": [
     "manifest"
    ],
    "summary": "Assign a carrier to a manifest",
    "description": "",
    "operationId": "assignCarrierToManifest",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/dispatch_to_carrier": {
   "post": {
    "tags": [
     "manifest"
    ],
    "summary": "Dispatch a manifest to a carrier",
    "description": "",
    "operationId": "dispatchManifestToCarrier",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/assign_and_dispatch_to_carrier": {
   "post": {
    "tags": [
     "manifest"
    ],
    "summary": "Dispatch a manifest to a carrier",
    "description": "",
    "operationId": "assignAndDispatchManifestToCarrier",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/legs": {
   "get": {
    "tags": [
     "manifest",
     "leg"
    ],
    "summary": "Get legs by manifest ID",
    "description": "",
    "operationId": "getLegsByManifestID",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/add_legs": {
   "post": {
    "tags": [
     "manifest",
     "leg"
    ],
    "summary": "Bulk add legs to specified manifest",
    "description": "",
    "operationId": "bulkAddLegsByManifestID",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/payment": {
   "get": {
    "tags": [
     "manifest"
    ],
    "summary": "Get manifest payment by manifest ID",
    "description": "",
    "operationId": "getManifestPaymentByManifestID",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "manifest"
    ],
    "summary": "Update a manifest payment by manifest ID. Note - this endpoint does not affect manifest payment items",
    "description": "",
    "operationId": "updateManifestPaymentByManifestID",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/payment/items/upsert": {
   "put": {
    "tags": [
     "manifest"
    ],
    "summary": "Upsert payment items to a manifest payment. To update a payment, specify a valid id for the payment. Payments without ids will be created.",
    "description": "",
    "operationId": "upsertManifestPaymentItemsByManifestID",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/payment/items": {
   "delete": {
    "tags": [
     "manifest"
    ],
    "summary": "Delete manifest payment items by supplying an array of manifest payment item ids.",
    "description": "",
    "operationId": "deleteManifestPaymentItemsByManifestID",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/notes": {
   "post": {
    "tags": [
     "manifest"
    ],
    "summary": "Create notes event for a manifest by manifest ID",
    "description": "",
    "operationId": "createNotesByManifestID",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/stops": {
   "get": {
    "tags": [
     "manifest",
     "stop"
    ],
    "summary": "Get stops by manifest ID",
    "description": "",
    "operationId": "getStopsByManifestID",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/stops/{stopID}": {
   "get": {
    "tags": [
     "manifest",
     "stop"
    ],
    "summary": "Get manifest's stop by ID",
    "description": "",
    "operationId": "getManifestStopByID",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/manifests/{manifestID}/stops/{stopID}/update_schedule": {
   "put": {
    "tags": [
     "manifest",
     "stop"
    ],
    "summary": "Update manifest's stop schedule by ID",
    "description": "",
    "operationId": "updateManifestStopScheduleByID",
    "security": [
     {
      "roserocket_auth": [
       "manifests"
      ]
     }
    ]
   }
  },
  "/partner_carriers": {
   "get": {
    "tags": [
     "partner_carrier"
    ],
    "summary": "Search partner carriers",
    "description": "",
    "operationId": "searchPartnerCarriers"
   },
   "post": {
    "tags": [
     "partner_carrier"
    ],
    "summary": "Create a partner carrier",
    "description": "",
    "operationId": "createPartnerCarrier"
   }
  },
  "/partner_carriers/{partnerCarrierID}": {
   "get": {
    "tags": [
     "partner_carrier"
    ],
    "summary": "Get partner carrier by ID",
    "description": "",
    "operationId": "getPartnerCarrierByID"
   },
   "put": {
    "tags": [
     "partner_carrier"
    ],
    "summary": "Update partner carrier by ID",
    "description": "",
    "operationId": "updatePartnerCarrierByID"
   },
   "delete": {
    "tags": [
     "partner_carrier"
    ],
    "summary": "Delete partner carrier by ID",
    "description": "",
    "operationId": "deletePartnerCarrierByID"
   }
  },
  "/customers": {
   "get": {
    "tags": [
     "customer"
    ],
    "summary": "Search customers",
    "description": "",
    "operationId": "searchCustomers",
    "security": [
     {
      "roserocket_auth": [
       "customers"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "customer"
    ],
    "summary": "Create new customer",
    "description": "",
    "operationId": "createCustomer",
    "security": [
     {
      "roserocket_auth": [
       "customers"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}": {
   "get": {
    "tags": [
     "customer"
    ],
    "summary": "Get customer by ID",
    "description": "",
    "operationId": "getCustomerByID",
    "security": [
     {
      "roserocket_auth": [
       "customers"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "customer"
    ],
    "summary": "Update customer by ID",
    "description": "",
    "operationId": "updateCustomerByID",
    "security": [
     {
      "roserocket_auth": [
       "customers"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "customer"
    ],
    "summary": "Delete customer by ID",
    "description": "",
    "operationId": "deleteCustomerByID",
    "security": [
     {
      "roserocket_auth": [
       "customers"
      ]
     }
    ]
   }
  },
  "/customers/{customerExtID}/upsert": {
   "put": {
    "tags": [
     "customer"
    ],
    "summary": "Upsert customer by external ID",
    "description": "",
    "operationId": "upsertCustomerByID",
    "security": [
     {
      "roserocket_auth": [
       "customers"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/orders/{orderID}/spot_quote": {
   "post": {
    "tags": [
     "quote"
    ],
    "summary": "Create a spot quote for a customer's order",
    "description": "",
    "operationId": "createOrderSpotQuote",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  },
  "/customers/{customerID}/orders/{orderID}/quotes": {
   "post": {
    "tags": [
     "quote"
    ],
    "summary": "Generate new quotes for a customer's order",
    "description": "",
    "operationId": "generateOrderQuotes",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "quote"
    ],
    "summary": "Get existing quotes for a customer's order",
    "description": "",
    "operationId": "getOrderQuotes",
    "security": [
     {
      "roserocket_auth": [
       "orders"
      ]
     }
    ]
   }
  }
 },
 "securityDefinitions": {
  "roserocket_auth": {
   "type": "oauth2",
   "tokenUrl": "https://auth.roserocket.com/oauth2/token",
   "flow": "password",
   "scopes": {
    "orders": "manage orders",
    "customers": "manage customers",
    "legs": "manage legs",
    "manifests": "manage manifests"
   }
  },
  "jwt": {
   "description": "",
   "type": "apiKey",
   "name": "Authorization",
   "in": "header"
  }
 }
}